import os
import math
from PIL import Image

# --- CONFIGURATION ---
ICON_DIR = "assets/icons"
OUT_PNG = "assets/ui/ui_icons.png"
OUT_HPP = "modules/blades_ui/UI_Icons.hpp"
ICON_SIZE = 128 # Downscales the 512x512 masters for VRAM efficiency

# Get all PNGs and sort them alphabetically so IDs remain consistent
icons = sorted([f for f in os.listdir(ICON_DIR) if f.endswith('.png')])

# Calculate optimal square grid
grid_cols = math.ceil(math.sqrt(len(icons)))
grid_rows = math.ceil(len(icons) / grid_cols)

atlas_w = grid_cols * ICON_SIZE
atlas_h = grid_rows * ICON_SIZE
atlas = Image.new("RGBA", (atlas_w, atlas_h), (0, 0, 0, 0))

uv_data = []

print(f"Packing {len(icons)} icons into a {atlas_w}x{atlas_h} atlas...")

for i, icon_file in enumerate(icons):
    img = Image.open(os.path.join(ICON_DIR, icon_file)).convert("RGBA")
    # High-quality downscale
    img = img.resize((ICON_SIZE, ICON_SIZE), Image.Resampling.LANCZOS)
    
    col = i % grid_cols
    row = i // grid_cols
    x = col * ICON_SIZE
    y = row * ICON_SIZE
    
    atlas.paste(img, (x, y))
    
    # Calculate Normalized UVs (0.0 to 1.0)
    u0 = x / atlas_w
    v0 = y / atlas_h
    u1 = (x + ICON_SIZE) / atlas_w
    v1 = (y + ICON_SIZE) / atlas_h
    
    name = os.path.splitext(icon_file)[0].upper()
    uv_data.append(f"    {{ {u0}f, {v0}f, {u1}f, {v1}f }}, // {i}: {name}")

# Save the Atlas Texture
os.makedirs(os.path.dirname(OUT_PNG), exist_ok=True)
atlas.save(OUT_PNG)

# Save the C++ Header
os.makedirs(os.path.dirname(OUT_HPP), exist_ok=True)
with open(OUT_HPP, 'w') as f:
    f.write("#pragma once\n#include <glm/glm.hpp>\n\n")
    f.write("// AUTO-GENERATED BY pack_icons.py\n")
    f.write("namespace Crescendo::Modules::Icons {\n")
    f.write("inline const glm::vec4 ATLAS_UVS[] = {\n")
    f.write("\n".join(uv_data) + "\n")
    f.write("};\n}\n")

print(f"Successfully generated {OUT_PNG} and {OUT_HPP}!")